slippage:
  base_slippage_bps: 10
  k1_participation: 50
  k2_volatility: 40
fill_model:
  default_fill_ratio: 1.0
  limit_up_buy_fill_ratio: 0.2
  limit_down_sell_fill_ratio: 0.2
liquidity:
  participation_limit: 0.05
